/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as DeliveryRatesRouteImport } from './routes/delivery-rates'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotationsIndexRouteImport } from './routes/quotations.index'
import { Route as QuotationsNewRouteImport } from './routes/quotations.new'
import { Route as QuotationsIdRouteImport } from './routes/quotations.$id'
import { Route as OffersNewRouteImport } from './routes/offers.new'
import { Route as QuotationsIdEditRouteImport } from './routes/quotations.$id.edit'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRatesRoute = DeliveryRatesRouteImport.update({
  id: '/delivery-rates',
  path: '/delivery-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIndexRoute = QuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsNewRoute = QuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIdRoute = QuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersNewRoute = OffersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OffersRoute,
} as any)
const QuotationsIdEditRoute = QuotationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => QuotationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/customers': typeof CustomersRoute
  '/delivery-rates': typeof DeliveryRatesRoute
  '/locations': typeof LocationsRoute
  '/offers': typeof OffersRouteWithChildren
  '/suppliers': typeof SuppliersRoute
  '/offers/new': typeof OffersNewRoute
  '/quotations/$id': typeof QuotationsIdRouteWithChildren
  '/quotations/new': typeof QuotationsNewRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/quotations/$id/edit': typeof QuotationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/customers': typeof CustomersRoute
  '/delivery-rates': typeof DeliveryRatesRoute
  '/locations': typeof LocationsRoute
  '/offers': typeof OffersRouteWithChildren
  '/suppliers': typeof SuppliersRoute
  '/offers/new': typeof OffersNewRoute
  '/quotations/$id': typeof QuotationsIdRouteWithChildren
  '/quotations/new': typeof QuotationsNewRoute
  '/quotations': typeof QuotationsIndexRoute
  '/quotations/$id/edit': typeof QuotationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/customers': typeof CustomersRoute
  '/delivery-rates': typeof DeliveryRatesRoute
  '/locations': typeof LocationsRoute
  '/offers': typeof OffersRouteWithChildren
  '/suppliers': typeof SuppliersRoute
  '/offers/new': typeof OffersNewRoute
  '/quotations/$id': typeof QuotationsIdRouteWithChildren
  '/quotations/new': typeof QuotationsNewRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/quotations/$id/edit': typeof QuotationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/customers'
    | '/delivery-rates'
    | '/locations'
    | '/offers'
    | '/suppliers'
    | '/offers/new'
    | '/quotations/$id'
    | '/quotations/new'
    | '/quotations/'
    | '/quotations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/customers'
    | '/delivery-rates'
    | '/locations'
    | '/offers'
    | '/suppliers'
    | '/offers/new'
    | '/quotations/$id'
    | '/quotations/new'
    | '/quotations'
    | '/quotations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/customers'
    | '/delivery-rates'
    | '/locations'
    | '/offers'
    | '/suppliers'
    | '/offers/new'
    | '/quotations/$id'
    | '/quotations/new'
    | '/quotations/'
    | '/quotations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryRatesRoute: typeof DeliveryRatesRoute
  LocationsRoute: typeof LocationsRoute
  OffersRoute: typeof OffersRouteWithChildren
  SuppliersRoute: typeof SuppliersRoute
  QuotationsIdRoute: typeof QuotationsIdRouteWithChildren
  QuotationsNewRoute: typeof QuotationsNewRoute
  QuotationsIndexRoute: typeof QuotationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-rates': {
      id: '/delivery-rates'
      path: '/delivery-rates'
      fullPath: '/delivery-rates'
      preLoaderRoute: typeof DeliveryRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/': {
      id: '/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof QuotationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/new': {
      id: '/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof QuotationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/$id': {
      id: '/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof QuotationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/new': {
      id: '/offers/new'
      path: '/new'
      fullPath: '/offers/new'
      preLoaderRoute: typeof OffersNewRouteImport
      parentRoute: typeof OffersRoute
    }
    '/quotations/$id/edit': {
      id: '/quotations/$id/edit'
      path: '/edit'
      fullPath: '/quotations/$id/edit'
      preLoaderRoute: typeof QuotationsIdEditRouteImport
      parentRoute: typeof QuotationsIdRoute
    }
  }
}

interface OffersRouteChildren {
  OffersNewRoute: typeof OffersNewRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersNewRoute: OffersNewRoute,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

interface QuotationsIdRouteChildren {
  QuotationsIdEditRoute: typeof QuotationsIdEditRoute
}

const QuotationsIdRouteChildren: QuotationsIdRouteChildren = {
  QuotationsIdEditRoute: QuotationsIdEditRoute,
}

const QuotationsIdRouteWithChildren = QuotationsIdRoute._addFileChildren(
  QuotationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CustomersRoute: CustomersRoute,
  DeliveryRatesRoute: DeliveryRatesRoute,
  LocationsRoute: LocationsRoute,
  OffersRoute: OffersRouteWithChildren,
  SuppliersRoute: SuppliersRoute,
  QuotationsIdRoute: QuotationsIdRouteWithChildren,
  QuotationsNewRoute: QuotationsNewRoute,
  QuotationsIndexRoute: QuotationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
